# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 187de3bf0042feec90e548454ae3644f985c6d29a283d3270a0f456ef6e843d2a4c6d8f5e29294139dcc2f12e15273b71b447d42be6ecc0630f1b1bf63baa525

test:
  secret_key_base: 0e4d6a3346ef5c0d472e4952e4b0d5a181d7a0ea3406b7d8a6b57e4acd52018c14241cd2ff15d905868dfb7cf2101e962673d879f8aece05966630fcb15d3c39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
